from string import Template

from data.paths import (
    FINAL_LIVERPOOL_VS_WATFORD_WITH_RETWEETS_EXCLUDED_FILE_PATH,
    LIVERPOOL_VS_WATFORD_WITH_NON_ENGLISH_TWEETS_EXCLUDED_FILE_PATH,
    ORIGINAL_LIVERPOOL_VS_WATFORD_FILE_PATH,
)

PARENT_DIRECTORY = ".."
RELATIVE_FILE_PATH_TEMPLATE = Template(f"{PARENT_DIRECTORY}/$file_path")
RELATIVE_ORIGINAL_LIVERPOOL_VS_WATFORD_FILE_PATH = RELATIVE_FILE_PATH_TEMPLATE.substitute(
    file_path=ORIGINAL_LIVERPOOL_VS_WATFORD_FILE_PATH,
)
RELATIVE_LANGUAGE_FILTERED_TWEETS_LIVERPOOL_VS_WATFORD_FILE_PATH = RELATIVE_FILE_PATH_TEMPLATE.substitute(
    file_path=LIVERPOOL_VS_WATFORD_WITH_NON_ENGLISH_TWEETS_EXCLUDED_FILE_PATH,
)
RELATIVE_FINAL_LIVERPOOL_VS_WATFORD_WITH_RETWEETS_EXCLUDED_FILE_PATH = RELATIVE_FILE_PATH_TEMPLATE.substitute(
    file_path=FINAL_LIVERPOOL_VS_WATFORD_WITH_RETWEETS_EXCLUDED_FILE_PATH,
)
